include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    require_trailing_commas: true
    depend_on_referenced_packages: false
