name: oyt_front_widgets
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/nestorsgarzonc
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_riverpod: ^2.1.1
  font_awesome_flutter: ^10.3.0
  go_router: ^5.2.2
  lottie: ^2.0.0
  oyt_front_core:
    path: ../oyt_front_core
  oyt_front_table:
    path: ../oyt_front_table

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
